### ISSUE TITLE
error: package leon.x.xdarknet2 does not exist

### ISSUE THREAD

**Issue by tomriddle54** [xvolica/DarkNet-for-Android#1]
error android studio 3.3

**Comment by spaul13** [comment]
@syedmustafa54 did u get the CMake error?

Error:Error occurred while communicating with CMake server. Check log C:\Users\spaul\Downloads\DarkNet-for-Android-master\DarkNet-for-Android-master\app\.externalNativeBuild\cmake\debug\armeabi-v7a\cmake_server_log.txt for additional information.

**Comment by spaul13** [comment]
@syedmustafa54 getting the same error, r u able to solve that problem?

**Comment by tomriddle54** [comment]
No still the same error

**Comment by bharath79** [comment]
its referring to a file "R" which does not exist

**Comment by xvolica** [comment]
Due to the update of AS , something changes(maybe the ndk tool version or cmake version), yolo model can't be build well now. So the project can only do clean job and get this error.
